name: Test Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Code Coverege
      run: bash <(curl -s https://codecov.io/bash)

